import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Clipboard, PlugZap, RefreshCw, Search, X } from 'lucide-react';
import { DataPanel } from '../../components/DataPanel';
import { EmptyState } from '../../components/EmptyState';
import { platformApi, type PlatformEnvironment } from '../platform/api';
import { metricsApi, type MetricsCollectionMode, type MetricsDesiredState, type MetricsIntegrationView, type MetricsSourceAccess } from './api';

const sourceLabels = { kubernetes_infra: 'K8s Infra', host_infra: 'VM / 主机 Infra', log_derived: 'Logs-to-Metrics' } as const;
const modeLabels = { external_collector: '复用现有采集器', managed_collector: '平台受管采集器' } as const;

export function MetricsEnvironmentsPage() {
  const queryClient = useQueryClient();
  const [query, setQuery] = useState('');
  const [selectedEnvironmentId, setSelectedEnvironmentId] = useState('');
  const [connectEnvironment, setConnectEnvironment] = useState<PlatformEnvironment | null>(null);
  const environmentsQuery = useQuery({ queryKey: ['platform-environments'], queryFn: platformApi.listEnvironments, retry: false });
  const integrationsQuery = useQuery({ queryKey: ['metrics-integrations'], queryFn: metricsApi.listIntegrations, retry: false });
  const environments = environmentsQuery.data ?? [];
  const integrations = integrationsQuery.data ?? [];
  const integrationByEnvironment = useMemo(() => new Map(integrations.map((item) => [item.integration.environmentId, item])), [integrations]);

  useEffect(() => {
    if (selectedEnvironmentId && environments.some((item) => item.id === selectedEnvironmentId)) return;
    setSelectedEnvironmentId(environments[0]?.id ?? '');
  }, [environments, selectedEnvironmentId]);

  const rows = useMemo(() => {
    const keyword = query.trim().toLowerCase();
    return environments.filter((item) => !keyword || [item.name, item.id, item.stage].join(' ').toLowerCase().includes(keyword));
  }, [environments, query]);
  const selectedEnvironment = environments.find((item) => item.id === selectedEnvironmentId) ?? null;
  const selectedIntegration = selectedEnvironment ? integrationByEnvironment.get(selectedEnvironment.id) ?? null : null;

  function refresh() {
    void Promise.all([environmentsQuery.refetch(), integrationsQuery.refetch()]);
  }

  return <div className="console-workbench min-h-0 overflow-hidden">
    <div className="grid h-full min-h-0 grid-cols-1 xl:grid-cols-[minmax(660px,1fr)_400px]">
      <DataPanel title="环境接入" help="每个环境只有一个指标写入目标；K8s、VM 和日志派生来源共享环境身份。">
        {environmentsQuery.isLoading || integrationsQuery.isLoading ? <Skeleton /> : environmentsQuery.error || integrationsQuery.error ? <EmptyState title="环境指标接入加载失败" action={<button type="button" className="console-button" onClick={refresh}>重试</button>} /> : environments.length === 0 ? (
          <EmptyState title="尚未登记环境" action={<Link className="console-button console-button-primary" to="/platform/environments">前往环境管理</Link>} />
        ) : <div className="overflow-hidden rounded-md border border-outline bg-white">
          <div className="console-list-toolbar border-b border-outline">
            <label className="console-list-toolbar-search sm:w-[360px]"><span className="sr-only">搜索环境接入</span><Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted" /><input className="console-input h-8 w-full pl-8 text-xs" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索环境名称、ID、阶段" /></label>
            <button type="button" className="console-icon-button" onClick={refresh} aria-label="刷新环境接入" title="刷新环境接入"><RefreshCw className={`h-3.5 w-3.5 ${environmentsQuery.isFetching || integrationsQuery.isFetching ? 'animate-spin' : ''}`} /></button>
          </div>
          {rows.length === 0 ? <div className="py-12"><EmptyState title="未找到匹配环境" /></div> : <div className="overflow-auto"><table className="console-table w-full min-w-[660px] table-fixed"><colgroup><col className="w-[28%]" /><col className="w-[24%]" /><col className="w-[22%]" /><col className="w-[16%]" /><col className="w-[10%]" /></colgroup><thead><tr><th>环境</th><th>写入目标</th><th>指标来源</th><th>接入状态</th><th className="text-right">操作</th></tr></thead><tbody>{rows.map((environment) => {
            const integration = integrationByEnvironment.get(environment.id);
            return <tr key={environment.id} className={`cursor-pointer ${environment.id === selectedEnvironmentId ? 'console-selected-row' : ''}`} onClick={() => setSelectedEnvironmentId(environment.id)}><td><div className="truncate font-semibold">{environment.name}</div><div className="truncate font-mono text-[11px] text-muted">{environment.id}</div></td><td className="font-mono text-[11px] text-muted">{integration?.integration.destinationRef || '未选择'}</td><td className="text-xs text-muted">{integration ? `${integration.sourceAccesses.length} 个来源` : '待接入'}</td><td><Status connected={integration?.integration.desiredState === 'connected'} /></td><td className="text-right">{integration ? <button type="button" className="console-button h-7 px-2" onClick={(event) => { event.stopPropagation(); setSelectedEnvironmentId(environment.id); }}>查看</button> : <button type="button" className="console-button console-button-primary h-7 px-2" onClick={(event) => { event.stopPropagation(); setConnectEnvironment(environment); }}>接入</button>}</td></tr>;
          })}</tbody></table></div>}
        </div>}
      </DataPanel>
      <EnvironmentAccessDetail environment={selectedEnvironment} integration={selectedIntegration} onConnect={() => selectedEnvironment && setConnectEnvironment(selectedEnvironment)} />
    </div>
    {connectEnvironment ? <ConnectEnvironmentDialog environment={connectEnvironment} onClose={() => setConnectEnvironment(null)} onCreated={async () => { await queryClient.invalidateQueries({ queryKey: ['metrics-integrations'] }); setSelectedEnvironmentId(connectEnvironment.id); setConnectEnvironment(null); }} /> : null}
  </div>;
}

function EnvironmentAccessDetail({ environment, integration, onConnect }: { environment: PlatformEnvironment | null; integration: MetricsIntegrationView | null; onConnect: () => void }) {
  const queryClient = useQueryClient();
	const [handoffSource, setHandoffSource] = useState<MetricsSourceAccess | null>(null);
	const [managedSource, setManagedSource] = useState<MetricsSourceAccess | null>(null);
	const [editOpen, setEditOpen] = useState(false);
	const [assessment, setAssessment] = useState<Awaited<ReturnType<typeof metricsApi.assessSource>> | null>(null);
  const updateMutation = useMutation({ mutationFn: ({ source, mode }: { source: MetricsSourceAccess; mode: MetricsCollectionMode }) => metricsApi.updateSourceAccess(source.id, { collectionMode: mode }), onSuccess: async () => queryClient.invalidateQueries({ queryKey: ['metrics-integrations'] }) });
	const assessMutation = useMutation({ mutationFn: metricsApi.assessSource, onSuccess: setAssessment });
	const logDerivedMutation = useMutation({ mutationFn: metricsApi.enableLogDerivedSource, onSuccess: async () => queryClient.invalidateQueries({ queryKey: ['metrics-integrations'] }) });
	const reconcileMutation = useMutation({ mutationFn: metricsApi.reconcileSources, onSuccess: async () => queryClient.invalidateQueries({ queryKey: ['metrics-integrations'] }) });
  if (!environment) return <aside className="min-h-0 overflow-auto border-l border-outline bg-white p-4"><EmptyState title="请选择环境" /></aside>;
  return <aside className="min-h-0 overflow-auto border-l border-outline bg-white p-4" aria-label="环境指标接入详情"><div className="space-y-5"><div><div className="flex items-center justify-between gap-3"><h2 className="text-base font-semibold">{environment.name}</h2>{integration ? <Status connected={integration.integration.desiredState === 'connected'} /> : null}</div><div className="mt-1 font-mono text-[11px] text-muted">{environment.id}</div></div>
    {!integration ? <div className="rounded border border-dashed border-outline p-4"><div className="text-sm font-semibold">尚未接入指标</div><p className="mt-1 text-xs leading-5 text-muted">接入后，此环境的所有指标来源使用同一个 VMS 写入目标和稳定环境标签。</p><button type="button" className="console-button console-button-primary mt-3" onClick={onConnect}><PlugZap className="h-3.5 w-3.5" />接入环境指标</button></div> : <><section><div className="flex items-start justify-between gap-2"><div><div className="text-xs font-semibold text-muted">写入目标</div><div className="mt-1 font-mono text-xs">{integration.integration.destinationRef}</div></div><button type="button" className="console-button h-7 px-2" onClick={() => setEditOpen(true)}>调整接入</button></div><div className="mt-3 text-xs font-semibold text-muted">身份标签</div><div className="mt-1 font-mono text-xs">{integration.integration.identityLabelKey}={environment.id}</div></section><section className="border-t border-outline pt-4"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">指标来源</h3><div className="flex gap-1"><button type="button" className="console-button h-7 px-2" disabled={reconcileMutation.isPending} onClick={() => reconcileMutation.mutate(integration.integration.id)}><RefreshCw className={`h-3.5 w-3.5 ${reconcileMutation.isPending ? 'animate-spin' : ''}`} />同步环境资源</button>{integration.sourceAccesses.some((source) => source.sourceKind === 'log_derived') ? null : <button type="button" className="console-button h-7 px-2" disabled={logDerivedMutation.isPending} onClick={() => logDerivedMutation.mutate(integration.integration.id)}>启用 Logs-to-Metrics</button>}</div></div><div className="mt-3 space-y-2">{integration.sourceAccesses.length === 0 ? <div className="rounded border border-dashed border-outline p-3 text-xs text-muted">环境尚未绑定 K8s 集群或 VM 主机组。</div> : integration.sourceAccesses.map((source) => {
      const supportsManaged = source.sourceKind === 'kubernetes_infra';
      const currentAssessment = assessment?.sourceAccessId === source.id ? assessment : null;
		const latestRelease = integration.collectorReleases.find((release) => release.sourceAccessId === source.id);
      return <div key={source.id} className="rounded border border-outline p-3"><div className="flex items-center justify-between gap-3"><div className="text-xs font-semibold">{sourceLabels[source.sourceKind]}</div><Status connected={source.desiredState === 'connected'} /></div>{latestRelease ? <div className="mt-2 text-[11px] text-muted">受管发布 generation {latestRelease.generation} · {latestRelease.status === 'applied' ? '已应用' : latestRelease.status === 'previewed' ? '待确认' : '失败'}</div> : null}<button type="button" className="console-button mt-3 w-full" disabled={assessMutation.isPending} onClick={() => assessMutation.mutate(source.id)}><Search className="h-3.5 w-3.5" />{assessMutation.isPending ? '检测中' : '检测采集环境'}</button>{currentAssessment ? <div className="mt-2 rounded bg-surface px-2.5 py-2 text-xs leading-5 text-muted"><div>{currentAssessment.message}</div>{currentAssessment.detectedCollector ? <div className="mt-1 font-mono">collector: {currentAssessment.detectedCollector}</div> : null}{currentAssessment.detectedSignals.length ? <div className="font-mono">signals: {currentAssessment.detectedSignals.join(', ')}</div> : null}</div> : null}<label className="mt-3 block text-xs font-semibold text-muted">采集方式<select className="console-input mt-1 w-full" value={source.collectionMode} disabled={updateMutation.isPending} onChange={(event) => updateMutation.mutate({ source, mode: event.target.value as MetricsCollectionMode })}><option value="external_collector">{modeLabels.external_collector}</option>{supportsManaged ? <option value="managed_collector">{modeLabels.managed_collector}</option> : null}</select></label>{source.collectionMode === 'external_collector' ? <button type="button" className="console-button mt-3 w-full" onClick={() => setHandoffSource(source)}><Clipboard className="h-3.5 w-3.5" />查看接入片段</button> : <button type="button" className="console-button console-button-primary mt-3 w-full" onClick={() => setManagedSource(source)}>预览并部署 vmagent</button>}</div>;
    })}</div>{updateMutation.error ? <div className="mt-2 text-xs font-semibold text-danger">{errorMessage(updateMutation.error)}</div> : null}</section></>}
  </div>{handoffSource ? <HandoffDialog source={handoffSource} onClose={() => setHandoffSource(null)} /> : null}{managedSource ? <ManagedCollectorDialog source={managedSource} onClose={() => setManagedSource(null)} /> : null}{editOpen && integration ? <EditIntegrationDialog environment={environment} view={integration} onClose={() => setEditOpen(false)} /> : null}</aside>;
}

function EditIntegrationDialog({ environment, view, onClose }: { environment: PlatformEnvironment; view: MetricsIntegrationView; onClose: () => void }) {
	const queryClient = useQueryClient();
	const [destination, setDestination] = useState(view.integration.destinationRef);
	const [desiredState, setDesiredState] = useState(view.integration.desiredState);
	const destinations = useQuery({ queryKey: ['metrics-write-destinations', environment.id], queryFn: () => metricsApi.listWriteDestinationOptions(environment.id), retry: false });
	const mutation = useMutation({ mutationFn: () => metricsApi.updateIntegration(view.integration.id, { destinationRef: destination, desiredState }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['metrics-integrations'] }); onClose(); } });
	return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4" role="dialog" aria-modal="true" aria-labelledby="edit-integration-title"><div className="w-full max-w-lg rounded-lg border border-outline bg-white shadow-xl"><div className="flex items-center justify-between border-b border-outline px-4 py-3"><h2 id="edit-integration-title" className="text-base font-semibold">调整环境指标接入</h2><button type="button" className="console-icon-button" onClick={onClose} aria-label="关闭调整接入"><X className="h-4 w-4" /></button></div><div className="space-y-4 p-4"><label className="block text-sm font-semibold">写入目标<select className="console-input mt-1 w-full" value={destination} disabled={destinations.isLoading} onChange={(event) => setDestination(event.target.value)}>{(destinations.data ?? []).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.remoteWriteURL}</option>)}</select></label><label className="block text-sm font-semibold">连接状态<select className="console-input mt-1 w-full" value={desiredState} onChange={(event) => setDesiredState(event.target.value as MetricsDesiredState)}><option value="connected">已连接</option><option value="disconnected">断开</option></select></label>{mutation.error ? <div className="console-notice console-notice-danger">{errorMessage(mutation.error)}</div> : null}</div><div className="flex justify-end gap-2 border-t border-outline px-4 py-3"><button type="button" className="console-button" onClick={onClose}>取消</button><button type="button" className="console-button console-button-primary" disabled={!destination || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? '保存中' : '保存'}</button></div></div></div>;
}

function ManagedCollectorDialog({ source, onClose }: { source: MetricsSourceAccess; onClose: () => void }) {
  const [release, setRelease] = useState<Awaited<ReturnType<typeof metricsApi.previewManagedCollector>> | null>(null);
  const previewMutation = useMutation({ mutationFn: () => metricsApi.previewManagedCollector(source.id), onSuccess: setRelease });
  const applyMutation = useMutation({ mutationFn: () => metricsApi.applyManagedCollector(source.id), onSuccess: setRelease });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4" role="dialog" aria-modal="true" aria-labelledby="managed-title"><div className="w-full max-w-xl rounded-lg border border-outline bg-white shadow-xl"><div className="flex items-center justify-between border-b border-outline px-4 py-3"><div><h2 id="managed-title" className="text-base font-semibold">平台受管 vmagent</h2><p className="mt-0.5 text-xs text-muted">仅在该 K8s 集群没有可复用采集器时使用。</p></div><button type="button" className="console-icon-button" onClick={onClose} aria-label="关闭受管采集器"><X className="h-4 w-4" /></button></div><div className="space-y-3 p-4">{!release ? <div className="rounded border border-outline bg-surface p-3 text-xs leading-5 text-muted">平台将预览 Namespace、RBAC、ConfigMap 和 vmagent Deployment；发布仍经过 K8s 部署确认链路。</div> : <><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-muted">集群</span><div className="mt-1 font-mono">{release.clusterId}</div></div><div><span className="text-muted">命名空间</span><div className="mt-1 font-mono">{release.namespace}</div></div><div className="col-span-2"><span className="text-muted">镜像</span><div className="mt-1 break-all font-mono">{release.image}</div></div></div><div className="rounded border border-outline p-3"><div className="text-xs font-semibold">资源变更</div><ul className="mt-2 space-y-1 text-xs text-muted">{release.resources.map((resource) => <li key={`${resource.kind}/${resource.namespace}/${resource.name}`} className="font-mono">{resource.kind} {resource.namespace ? `${resource.namespace}/` : ''}{resource.name}</li>)}</ul></div></>}{previewMutation.error || applyMutation.error ? <div className="console-notice console-notice-danger">{errorMessage(previewMutation.error || applyMutation.error)}</div> : null}</div><div className="flex justify-end gap-2 border-t border-outline px-4 py-3"><button type="button" className="console-button" onClick={onClose}>取消</button>{!release ? <button type="button" className="console-button console-button-primary" disabled={previewMutation.isPending} onClick={() => previewMutation.mutate()}>{previewMutation.isPending ? '预览中' : '生成部署预览'}</button> : release.status === 'previewed' ? <button type="button" className="console-button console-button-primary" disabled={applyMutation.isPending} onClick={() => applyMutation.mutate()}>{applyMutation.isPending ? '部署中' : '确认部署'}</button> : <button type="button" className="console-button console-button-primary" onClick={onClose}>完成</button>}</div></div></div>;
}

function HandoffDialog({ source, onClose }: { source: MetricsSourceAccess; onClose: () => void }) {
  const handoffQuery = useQuery({ queryKey: ['metrics-source-handoff', source.id], queryFn: () => metricsApi.getSourceHandoff(source.id), retry: false });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4" role="dialog" aria-modal="true" aria-labelledby="handoff-title"><div className="flex max-h-[82vh] w-full max-w-3xl flex-col rounded-lg border border-outline bg-white shadow-xl"><div className="flex items-center justify-between border-b border-outline px-4 py-3"><div><h2 id="handoff-title" className="text-base font-semibold">复用现有采集器</h2><p className="mt-0.5 text-xs text-muted">平台只交付目标和环境身份，抓取对象仍由现有采集体系管理。</p></div><button type="button" className="console-icon-button" onClick={onClose} aria-label="关闭接入片段"><X className="h-4 w-4" /></button></div><div className="min-h-0 overflow-auto p-4">{handoffQuery.isLoading ? <Skeleton /> : handoffQuery.error ? <div className="console-notice console-notice-danger">{errorMessage(handoffQuery.error)}</div> : <div className="space-y-4"><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-muted">资源</span><div className="mt-1 font-mono">{handoffQuery.data?.resourceRef}</div></div><div><span className="text-muted">环境身份</span><div className="mt-1 font-mono">novaapm_environment_id={handoffQuery.data?.environmentId}</div></div></div>{handoffQuery.data?.artifacts.map((artifact) => <section key={artifact.kind}><div className="mb-1.5 flex items-center justify-between"><h3 className="text-xs font-semibold">{artifact.kind}</h3><button type="button" className="console-button h-7 px-2" onClick={() => void navigator.clipboard.writeText(artifact.content)}>复制</button></div><pre className="overflow-auto rounded border border-outline bg-slate-950 p-3 text-[11px] leading-5 text-slate-100">{artifact.content}</pre><p className="mt-1 text-xs leading-5 text-muted">{artifact.note}</p></section>)}</div>}</div><div className="flex justify-end border-t border-outline px-4 py-3"><button type="button" className="console-button" onClick={onClose}>完成</button></div></div></div>;
}

function ConnectEnvironmentDialog({ environment, onClose, onCreated }: { environment: PlatformEnvironment; onClose: () => void; onCreated: () => void }) {
  const [destination, setDestination] = useState('');
  const optionsQuery = useQuery({ queryKey: ['metrics-write-destinations', environment.id], queryFn: () => metricsApi.listWriteDestinationOptions(environment.id), retry: false });
  const mutation = useMutation({ mutationFn: () => metricsApi.createIntegration({ environmentId: environment.id, destinationRef: destination }), onSuccess: onCreated });
  const options = optionsQuery.data ?? [];
  useEffect(() => { if (!destination && options[0]) setDestination(options[0].id); }, [destination, options]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4" role="dialog" aria-modal="true" aria-labelledby="connect-environment-title"><div className="w-full max-w-lg rounded-lg border border-outline bg-white shadow-xl"><div className="flex items-center justify-between border-b border-outline px-4 py-3"><h2 id="connect-environment-title" className="text-base font-semibold">接入环境指标</h2><button type="button" className="console-icon-button" onClick={onClose} aria-label="关闭接入环境"><X className="h-4 w-4" /></button></div><div className="space-y-4 p-4"><div><div className="text-sm font-semibold">{environment.name}</div><div className="mt-1 font-mono text-[11px] text-muted">{environment.id}</div></div>{optionsQuery.isLoading ? <Skeleton /> : optionsQuery.error ? <div className="console-notice console-notice-danger">{errorMessage(optionsQuery.error)}</div> : options.length === 0 ? <div className="rounded border border-dashed border-outline p-4 text-xs text-muted">暂无可用 VictoriaMetrics 写入目标。请先在平台观测接入配置中登记并启用 VMS。</div> : <label className="block text-sm font-semibold">写入目标<select className="console-input mt-1 w-full" value={destination} onChange={(event) => setDestination(event.target.value)}>{options.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.remoteWriteURL}</option>)}</select></label>}{mutation.error ? <div className="text-xs font-semibold text-danger">{errorMessage(mutation.error)}</div> : null}<div className="rounded border border-outline bg-surface px-3 py-2 text-xs leading-5 text-muted">创建后，平台根据已绑定的 K8s 集群和 VM 主机组生成来源接入计划；不会自动修改现有采集器。</div></div><div className="flex justify-end gap-2 border-t border-outline px-4 py-3"><button type="button" className="console-button" onClick={onClose}>取消</button><button type="button" className="console-button console-button-primary" disabled={!destination || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? '接入中' : '确认接入'}</button></div></div></div>;
}

function Status({ connected }: { connected: boolean }) { return <span className={`inline-flex items-center gap-1 text-xs font-semibold ${connected ? 'text-success' : 'text-muted'}`}><span className={`h-1.5 w-1.5 rounded-full ${connected ? 'bg-success' : 'bg-muted'}`} />{connected ? '已接入' : '未接入'}</span>; }
function Skeleton() { return <div className="space-y-2"><div className="h-8 rounded bg-surface" /><div className="h-10 rounded bg-surface" /><div className="h-10 rounded bg-surface" /></div>; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message : '操作失败'; }
