import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const layoutSource = readFileSync(new URL('./PlatformLayout.tsx', import.meta.url), 'utf8');
const navigationSource = readFileSync(new URL('./platformNavigation.ts', import.meta.url), 'utf8');
const observabilitySource = readFileSync(new URL('./ObservabilitySettingsPage.tsx', import.meta.url), 'utf8');
const helpTipSource = readFileSync(new URL('../../components/HelpTip.tsx', import.meta.url), 'utf8');
const platformSettingsSource = readFileSync(new URL('./PlatformSettingsPage.tsx', import.meta.url), 'utf8');
const styleSource = readFileSync(new URL('../../styles/index.css', import.meta.url), 'utf8');

test('平台管理左侧 Rail 直接承载五个身份与授权二级入口', () => {
  assert.equal(layoutSource.includes('/platform/settings'), true);
  assert.equal(layoutSource.includes('平台设置'), true);
  assert.equal(layoutSource.includes('platformAccessNavigationItems'), true);
  assert.equal(navigationSource.includes('/platform/identities'), true);
  assert.equal(navigationSource.includes('/platform/admins'), true);
  assert.equal(navigationSource.includes('/platform/product-access'), true);
  assert.equal(navigationSource.includes('/platform/k8s-access-profiles'), true);
  assert.equal(navigationSource.includes('/platform/break-glass'), true);
  assert.equal(navigationSource.includes('用户与用户组'), true);
  assert.equal(navigationSource.includes('平台管理员授权'), true);
  assert.equal(navigationSource.includes('产品访问授权'), true);
  assert.equal(navigationSource.includes('K8s 集群授权'), true);
  assert.equal(navigationSource.includes('K8s 紧急访问'), true);
  assert.equal(layoutSource.includes('/platform/observability'), false);
  assert.equal(layoutSource.includes('观测接入配置'), false);
  assert.equal(layoutSource.includes('平台管理导航'), true);
  assert.equal(layoutSource.includes('ModuleWorkbench'), true);
  assert.equal(layoutSource.includes('module="platform"'), true);
  assert.equal(layoutSource.includes('module-navigation-bar'), false);
  assert.equal(layoutSource.includes('module-navigation-tabs'), false);
  assert.equal(layoutSource.includes('module-navigation-title'), false);
  assert.equal(layoutSource.includes('platformSettingsItems'), false);
  assert.equal(layoutSource.includes('关闭平台设置菜单'), false);
  assert.equal(layoutSource.includes('<aside'), false);
  assert.equal(layoutSource.includes('xl:grid-cols-[248px'), false);
  assert.equal(styleSource.includes(":has(> .module-rail-expanded)"), true);
  assert.equal(styleSource.includes('padding-left: 232px'), true);
});

test('平台设置页面承载平台级镜像模板而非业务或项目配置', () => {
	assert.equal(platformSettingsSource.includes("queryKey: ['platform-grafana-setting']"), true);
	assert.equal(platformSettingsSource.includes('platformApi.getGrafanaSetting'), true);
	assert.equal(platformSettingsSource.includes('platformApi.updateGrafanaSetting'), true);
	assert.equal(platformSettingsSource.includes('title="Grafana 工作区"'), true);
	assert.equal(platformSettingsSource.includes('Grafana 入口地址'), true);
	assert.equal(platformSettingsSource.includes('平台嵌入时自动强制 kiosk=1'), true);
	assert.equal(platformSettingsSource.includes('/dashboards'), true);
	assert.equal(platformSettingsSource.includes('/explore'), true);
  assert.equal(platformSettingsSource.includes("queryKey: ['platform-images']"), true);
  assert.equal(platformSettingsSource.includes('platformApi.listImages'), true);
  assert.equal(platformSettingsSource.includes('platformApi.updateImage'), true);
  assert.equal(platformSettingsSource.includes('module-navigation-bar'), false);
  assert.equal(platformSettingsSource.includes('module-navigation-link'), false);
  assert.equal(platformSettingsSource.includes('PlatformSettingsTabButton'), false);
  assert.equal(platformSettingsSource.includes('aria-current={active ? \'page\' : undefined}'), false);
  assert.equal(platformSettingsSource.includes('title="平台设置"'), false);
  assert.equal(platformSettingsSource.includes('镜像模板'), true);
  assert.equal(platformSettingsSource.includes('title="镜像模板"'), true);
  assert.equal(platformSettingsSource.includes('镜像模板会在部署清单渲染时作为平台级运行配置使用'), true);
  assert.equal(platformSettingsSource.includes('__NOVAAPM_IMAGE_OTEL_COLLECTOR__'), true);
  assert.equal(platformSettingsSource.includes('__NOVAAPM_IMAGE_VMALERT__'), true);
  assert.equal(platformSettingsSource.includes('日志采集 DaemonSet'), true);
  assert.equal(platformSettingsSource.includes('日志告警 vmalert Runtime'), true);
  assert.equal(platformSettingsSource.includes('<aside'), false);
  assert.equal(platformSettingsSource.includes('platformSettingGroups'), false);
  assert.equal(platformSettingsSource.includes('console-selected-row'), true);
  assert.equal(platformSettingsSource.includes('table-fixed'), true);
  assert.equal(platformSettingsSource.includes('platform-settings-table'), true);
  assert.equal(styleSource.includes('.platform-settings-table th'), true);
  assert.equal(styleSource.includes('.platform-settings-table td'), true);
  assert.equal(platformSettingsSource.includes('max-w-[1480px]'), true);
  assert.equal(platformSettingsSource.includes('<colgroup>'), true);
  assert.equal(platformSettingsSource.includes('console-detail-rail'), false);
  assert.equal(platformSettingsSource.includes('xl:grid-cols-[minmax(0,1fr)_360px]'), false);
  assert.equal(platformSettingsSource.includes('editingKey'), true);
  assert.equal(platformSettingsSource.includes('beginEdit'), true);
  assert.equal(platformSettingsSource.includes('updateMutation.reset()'), true);
  assert.equal(platformSettingsSource.includes('event.stopPropagation()'), true);
  assert.equal(platformSettingsSource.includes('搜索模板、占位符、镜像'), true);
  assert.equal(platformSettingsSource.includes('filteredRows'), true);
  assert.equal(platformSettingsSource.includes('pagedRows'), true);
  assert.equal(platformSettingsSource.includes('pageSize'), true);
  assert.equal(platformSettingsSource.includes('上一页'), true);
  assert.equal(platformSettingsSource.includes('下一页'), true);
  assert.equal(platformSettingsSource.includes('未找到匹配的镜像模板'), true);
  assert.equal(platformSettingsSource.includes('生效范围'), true);
  assert.equal(platformSettingsSource.includes('ImageScopeTag'), true);
  assert.equal(platformSettingsSource.includes('title={scope}'), true);
  assert.equal(platformSettingsSource.includes('title={item.value}'), true);
  assert.equal(platformSettingsSource.includes('title={item.key}'), true);
  assert.equal(platformSettingsSource.includes('刷新镜像模板'), true);
  assert.equal(platformSettingsSource.includes('console-icon-button'), true);
  assert.equal(platformSettingsSource.includes('修改'), true);
  assert.equal(platformSettingsSource.includes('保存'), true);
  assert.equal(platformSettingsSource.includes('取消'), true);
  assert.equal(platformSettingsSource.includes('min-h-[560px]'), false);
  assert.equal(platformSettingsSource.includes('min-h-[520px]'), false);
  assert.equal(platformSettingsSource.includes('min-h-[360px]'), false);
  assert.equal(platformSettingsSource.includes('业务'), false);
  assert.equal(platformSettingsSource.includes('项目'), false);
});

test('观测接入配置按领域维护日志和指标写入端点', () => {
  assert.equal(observabilitySource.includes("queryKey: ['observability-endpoints', domain]"), true);
  assert.equal(observabilitySource.includes('listEndpointsByDomain(domain)'), true);
  assert.equal(observabilitySource.includes('logsApi.listEndpoints'), true);
  assert.equal(observabilitySource.includes('observabilityEndpointsApi.listVictoriaMetrics'), true);
  assert.equal(observabilitySource.includes('logsApi.createEndpoint'), true);
  assert.equal(observabilitySource.includes('logsApi.updateEndpoint'), true);
  assert.equal(observabilitySource.includes('observabilityEndpointsApi.createVictoriaMetrics'), true);
  assert.equal(observabilitySource.includes('observabilityEndpointsApi.updateVictoriaMetrics'), true);
  assert.equal(observabilitySource.includes("if (domain === 'metrics')"), true);
  assert.equal(observabilitySource.includes("if (form.sinkType !== 'vm')"), true);
  assert.equal(observabilitySource.includes("if (form.sinkType === 'vm')"), true);
  assert.match(observabilitySource, /useEffect\(\(\) => \{[\s\S]*setQuery\(''\)[\s\S]*setForm\(createEmptyEndpoint\(domain\)\)[\s\S]*\}, \[domain\]\)/);
  assert.equal(observabilitySource.includes('console-table'), true);
  assert.equal(observabilitySource.includes('EndpointTableRow'), true);
  assert.equal(observabilitySource.includes('EndpointDetailDrawer'), true);
  assert.equal(observabilitySource.includes('新增${domainLabel}'), true);
  assert.equal(observabilitySource.includes('编辑${domainLabel}'), true);
  assert.equal(observabilitySource.includes('EndpointFormSection'), true);
  assert.equal(observabilitySource.includes('端点身份'), true);
  assert.equal(observabilitySource.includes('地址配置'), true);
  assert.equal(observabilitySource.includes('租户与凭据'), false);
  assert.equal(observabilitySource.includes('EndpointExampleHelp'), true);
  assert.equal(observabilitySource.includes('<details'), false);
  assert.equal(observabilitySource.includes('<summary'), false);
  assert.equal(helpTipSource.includes('group-hover'), true);
  assert.equal(helpTipSource.includes('group-focus-within'), true);
  assert.equal(observabilitySource.includes('写入地址示例'), true);
  assert.equal(observabilitySource.includes('查询地址示例'), true);
  assert.equal(observabilitySource.includes('OTel / OTLP'), true);
  assert.equal(observabilitySource.includes('http://otel-gateway:4318/v1/logs'), true);
  assert.equal(observabilitySource.includes('查询由最终存储后端提供'), true);
  assert.equal(observabilitySource.includes('/insert/opentelemetry/v1/logs'), true);
  assert.equal(observabilitySource.includes('/select/logsql/query'), true);
  assert.equal(observabilitySource.includes('/_bulk'), true);
  assert.equal(observabilitySource.includes('/_search'), true);
  assert.equal(observabilitySource.includes('AccountID'), false);
  assert.equal(observabilitySource.includes('ProjectID'), false);
  assert.equal(observabilitySource.includes('Secret Ref'), false);
  assert.equal(observabilitySource.includes('secretRef'), false);
  assert.equal(observabilitySource.includes('生成租户 ID'), false);
  assert.equal(observabilitySource.includes('K8s 集群'), true);
  assert.equal(observabilitySource.includes('请选择已登记集群'), true);
  assert.equal(observabilitySource.includes('端点只能绑定已登记的 K8s 集群'), true);
  assert.equal(observabilitySource.includes('placeholder="test03"'), false);
  assert.equal(observabilitySource.includes('默认 Alertmanager URL'), false);
  assert.equal(observabilitySource.includes('Alertmanager notify URL'), false);
  assert.equal(observabilitySource.includes('k8sApi.listClusters'), true);
  assert.equal(observabilitySource.includes('k8sApi.listNamespaces'), false);
  assert.equal(observabilitySource.includes('查看'), true);
  assert.equal(observabilitySource.includes('查询能力'), true);
  assert.equal(observabilitySource.includes('NovaAPM Alert Ingest URL'), false);
  assert.equal(observabilitySource.includes('Runtime 固定部署到平台 namespace'), false);
  assert.equal(observabilitySource.includes('部署 Runtime'), false);
  assert.equal(observabilitySource.includes('生成 YAML'), false);
  assert.equal(observabilitySource.includes('确认部署'), false);
  assert.equal(observabilitySource.includes('预览 Runtime'), false);
  assert.equal(observabilitySource.includes('部署 vmalert Runtime 需要填写 NovaAPM Alert Ingest URL'), false);
  assert.equal(observabilitySource.includes('请先填写并保存 Alertmanager URL'), false);
  assert.equal(observabilitySource.includes('ClusterCollectorConfigPanel'), false);
  assert.equal(observabilitySource.includes('集群 Collector 基础配置'), false);
  assert.equal(observabilitySource.includes('logsApi.getClusterConfig'), false);
  assert.equal(observabilitySource.includes('logsApi.upsertClusterConfig'), false);
});

test('观测接入配置提供 VictoriaMetrics 写入目标表单', () => {
  assert.match(observabilitySource, /VictoriaMetrics/);
  assert.match(observabilitySource, /Remote Write 地址/);
  assert.match(observabilitySource, /observabilityEndpointsApi\.createVictoriaMetrics/);
  assert.match(observabilitySource, /observabilityEndpointsApi\.test/);
});
